name: All platform build test

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC",
            os: windows-latest,
            build_type: "Release", cc: "cl", cxx: "cl",
            #this path will change at some point when VC2022 is released I guess
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
          - {
            name: "Ubuntu gcc",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
          - {
            name: "Ubuntu clang",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }
          - {
            name: "MacOS gcc",
            os: macos-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test on Windows
        if: startsWith(matrix.config.os, 'windows')
        working-directory: ${{github.workspace}}/build
        run: tests/${{env.BUILD_TYPE}}/test_libnetcpp.exe

      - name: Test on Linux/MacOS
        if: (!startsWith(matrix.config.os, 'windows'))
        working-directory: ${{github.workspace}}/build
        run: tests/test_libnetcpp